#!/bin/bash

set -e

if [ "$1" == "dev" ] || [ "$1" == "staging" ] || [ "$1" == "production" ]; then
    pyvenv env
    source env/bin/activate

    if [ "$1" == "dev" ]; then
        source etc/environments/development/env
    elif [ "$1" == "staging" ]; then
        source etc/environments/staging/env
    elif [ "$1" == "production" ]; then
        source etc/environments/production/env
    fi

else
    echo ""
    echo -e "WARNING!\033[0;31m You did not pass an environment. \033[0m";
    echo -e "Please try again using 'dev' or 'staging' or 'production'."
    echo ""
    exit
fi

pip install -r requirements.txt

npm install
npm run build

if [ "$1" == "staging" ] || [ "$1" == "production" ]; then
    python manage.py collectstatic --noinput
fi
