#!/usr/bin/env bash

set -e

if [ "$1" == "dev" ] || [ "$1" == "prod" ]; then
    source env/bin/activate
    if [ "$1" == "dev" ]; then
        source etc/environments/development/env
    elif [ "$1" == "prod" ]; then
        source etc/environments/production/env
    fi

    python manage.py runserver 0.0.0.0:8000
else
    echo ""
    echo -e "WARNING!\033[0;31m You did not pass an environment. \033[0m";
    echo -e "Please try again using 'dev' or 'prod'"
    echo ""
fi
