#!/usr/bin/env bash

set -e

export PATH=env/bin:${PATH}
export DATABASE_URL=postgres://localhost/bwedb
export DEBUG=true
export DJANGO_SETTINGS_MODULE=project.settings
export EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend


flake8 project --ignore=E128,E501 --exclude=migrations,settings

npm test
